import base from '@repo/eslint-config/base';

export default [
  ...base,
  // Generated by `wrangler types`; its own eslint-disable header is what the
  // linter complains about.
  { ignores: ['worker-configuration.d.ts'] },
];
